---
- hosts: all
  roles:
    - embedable-jar
  serial: 1

  vars_files:
    - "variables_global.yml"
    - "roles/embedable-jar/vars/{{ project_artifact_id }}/global.yml"
    - "roles/embedable-jar/vars/{{ project_artifact_id }}/{{ env }}.yml"
