---
- hosts: "{{ project_artifact_id }}"
  roles:
    - tomcat
  vars_files:
    - "variables_global.yml"
    - [ "roles/tomcat/vars/{{ project_artifact_id }}/global.yml", "variables_empty.yml" ]
    - [ "roles/tomcat/vars/{{ project_artifact_id }}/{{ env }}.yml", "variables_empty.yml" ]
    - [ "roles/tomcat/vars/{{ project_artifact_id }}/{{ env }}-vault.yml", "variables_empty.yml" ]
    - [ "roles/tomcat/vars/{{ project_artifact_id }}/{{ inventory_hostname }}", "variables_empty.yml" ]
