---
# tasks file for codedeploy
- name: Installs and starts the AWS CodeDeploy Agent
#  aws_codedeploy: 
#    enabled: 1  
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - ruby
    - wget
  tags: always
    
- name: Wget the installer
  shell:  cd /home/ec2-user && wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install && chmod +x install && ./install auto
  tags: always
  
- name: Start and enabled
  service:
    name:  codedeploy-agent
    enabled: yes
    state: started
  tags: always
    
